version: '3.3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - db

  php:
    restart: unless-stopped
    image: grafikart/php:1.0.4
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - db

  db:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - 5432:5432
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monody
      TZ: Europe/Paris
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
      
  node:
    restart: unless-stopped
    build:
      context: ./docker/node
    command: yarn run dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
  
  node_server:
    restart: unless-stopped
    build: 
      context: ./docker/node
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

volumes:
  db-data:
    driver: local