services:
  web:
    image: macbre/nginx-http3:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./cert.key:/etc/nginx/cert.key
    links:
      - php
    networks:
      - monody

  php:
    restart: unless-stopped
    build:
      context: docker/prod/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    networks:
      - monody

  websockets:
    restart: unless-stopped
    build:
      context: docker/prod/websockets
    volumes:
      - .:/var/www:delegated
    ports:
      - "6001:6001"
    networks:
      - monody

  db:
    restart: unless-stopped
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monody
      TZ: Europe/Paris
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - monody

  redis:
    restart: unless-stopped
    image: redis:alpine
    networks:
      - monody

networks:
  monody:
    driver: bridge

volumes:
  db-data:
    driver: local
