services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - monody

  php:
    restart: unless-stopped
    image: grafikart/php:php8.1-1
    build:
      context: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    networks:
      - monody

  websockets:
    restart: unless-stopped
    build:
      context: ./docker/websockets
    volumes:
      - .:/var/www:delegated
    working_dir: /var/www
    command: yarn run serve
    ports:
      - "6001:6001"
    networks:
      - monody

  db:
    restart: unless-stopped
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monody
      TZ: Europe/Paris
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - monody

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8888:8080"

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - monody

  mix:
    restart: unless-stopped
    build:
      context: ./docker/mix
    command: yarn run watch
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app

networks:
  monody:
    driver: bridge

volumes:
  db-data:
    driver: local
