version: '3.3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - db

  php:
    restart: unless-stopped
    image: grafikart/php:1.0.4
    build:
      context: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    links:
      - db
      - adminer

  websockets:
    restart: unless-stopped
    build:
      context: ./docker/websockets
    volumes:
      - .:/var/www:delegated
    ports:
      - "6001:6001"

  db:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monody
      TZ: Europe/Paris
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8888:8080"

  node_server:
    restart: unless-stopped
    build:
      context: ./docker/node
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app:delegated
    ports:
      - "5000:5000"

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
    driver: local
