name: 'Run code fixer'
on: [push]
jobs:
  Fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: make install
      - name: Run fixer
        run: make format